# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shane Gerhardt
email: shane.gerhardt@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Hire Web Developer Shane Gerhardt for your project.
  Get free quotes from a professional near San Francisco, California.
baseurl: "http://shanegerhardt.com" # the subpath of your site, e.g. /blog
url: "http://shanegerhardt.com" # the base hostname & protocol for your site
twitter_username: SeeShaneTweet
github_username:  shanegerhardt
linkedin_username:  shanegerhardt

# Build settings
markdown: kramdown
sass:
  style: compressed
